version: "3"
services:
  susy_sign_direct_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_sign_direct_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x746ab504C722292E43520d5FDA6Fd2c79a046065
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_sign_reverse_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_sign_reverse_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=3PLN7YKkWMjFNXqTTFYRMgS3D1HfZ1tL6XN
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_sign_direct_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_sign_direct_extractor
    tty: true
    restart: always
    command: --config sign_bsc.json --type "waves-based-to-eth-direct"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8190:8090"
    networks:
      - app-network
  susy_sign_reverse_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_sign_reverse_extractor
    tty: true
    command: --config sign_bsc.json --type "waves-based-to-eth-reverse"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8191:8090"
    networks:
      - app-network
  susy_bsc_usdn_direct_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_bsc_usdn_direct_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x3a9e63494D6258FEEAA2a348C519cc14C6df8827
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_bsc_usdn_reverse_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_bsc_usdn_reverse_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=3P5SKDHPTBF1Spe1nzEA11GFjfuv1V59zVd
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_bsc_usdn_direct_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_bsc_usdn_direct_extractor
    tty: true
    restart: always
    command: --config usdn_bsc.json --type "waves-based-to-eth-direct"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8323:8090"
    networks:
      - app-network
  susy_bsc_usdn_reverse_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_bsc_usdn_reverse_extractor
    tty: true
    restart: always
    command: --config usdn_bsc.json --type "waves-based-to-eth-reverse"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8324:8090"
    networks:
      - app-network
  susy_ethereum_solana_gton_direct_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_ethereum_solana_gton_direct_extractor
    tty: true
    restart: always
    command: --config gton_eth_solana.json --type "evm-based-to-solana-direct"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8321:8090"
    networks:
      - app-network
  susy_ethereum_solana_gton_reverse_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_ethereum_solana_gton_reverse_extractor
    tty: true
    restart: always
    command: --config gton_eth_solana.json --type "evm-based-to-solana-reverse"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8322:8090"
    networks:
      - app-network
  susy_ethereum_solana_gton_direct_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_ethereum_solana_gton_direct_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=9Je9bU2wSqmCFWVYv8prcMyrPhQbwAvmwrjz4s6itd1j
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_ethereum_solana_gton_reverse_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_ethereum_solana_gton_reverse_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0xbc5a6045d012bcae3996d612f7c7ded48adec5a6
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  graviton_gton_lp_locking_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: graviton_gton_lp_locking_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x2FAC2013Fc3a9ca6e0a9FD84037b3DD0d3ceD57A
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  relay_token_fantom_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: relay_token_fantom_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0xa7a1869df83968986c383bfE54432475014AaEeA
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  relay_token_binance_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: relay_token_binance_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0xAA7D9DD236F2E649A431A6ec157065683A60E2d5
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  relay_token_polygon_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: relay_token_polygon_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0xbF017F8aB3a3AB41b59cA2606D8057584b50f64b
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  relay_token_heco_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: relay_token_heco_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x1E2327842A5aE79230d2217422065Bd709809E76
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  relay_token_xdai_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: relay_token_xdai_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x49b6431BDcd6CFaf79a3a5309261cB268642d8C0
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  relay_token_avax_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: relay_token_avax_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x154c0859b1a74dBf57cad422847c77F6C8D33E0C
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
