version: "3"
services:
  susy_sign_direct_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_sign_direct_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x746ab504C722292E43520d5FDA6Fd2c79a046065
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_sign_reverse_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_sign_reverse_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=3PLN7YKkWMjFNXqTTFYRMgS3D1HfZ1tL6XN
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_sign_direct_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_sign_direct_extractor
    tty: true
    restart: always
    command: --config sign_bsc.json --type "waves-evm-direct"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8190:8090"
    networks:
      - app-network
  susy_sign_reverse_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_sign_reverse_extractor
    tty: true
    command: --config sign_bsc.json --type "waves-evm-reverse"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8191:8090"
    networks:
      - app-network
  susy_heco_usdn_direct_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_heco_usdn_direct_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x497299613eDBD6aA5461d3A3de5843B33e2798B3
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_heco_usdn_reverse_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_heco_usdn_reverse_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=3PLRJ8W321thTdrKuQzxkuvF7RUYDoSrLvM
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_heco_usdn_direct_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_heco_usdn_direct_extractor
    tty: true
    restart: always
    command: --config usdn_heco.json --type "waves-evm-direct"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8290:8090"
    networks:
      - app-network
  susy_heco_usdn_reverse_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_heco_usdn_reverse_extractor
    tty: true
    restart: always
    command: --config usdn_heco.json --type "waves-evm-reverse"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8291:8090"
    networks:
      - app-network
  susy_ftm_usdn_direct_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_ftm_usdn_direct_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0xcBC5FC99Ff12Ae77c0F712805134bd0abAeee609
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_ftm_usdn_reverse_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_ftm_usdn_reverse_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=3P2UzKyojeQuZ9PrSL9am4L7YWGX3goownZ
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_ftm_usdn_direct_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_ftm_usdn_direct_extractor
    tty: true
    restart: always
    command: --config usdn_ftm.json --type "waves-evm-direct"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8300:8090"
    networks:
      - app-network
  susy_ftm_usdn_reverse_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_ftm_usdn_reverse_extractor
    tty: true
    restart: always
    command: --config usdn_ftm.json --type "waves-evm-reverse"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8301:8090"
    networks:
      - app-network
  susy_avax_usdn_direct_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_avax_usdn_direct_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x97D58D2c46F77D245bbe36e2D3DAD14e929f9bc2
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_avax_usdn_reverse_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_avax_usdn_reverse_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=3PLnuvyzpTmQUTDSEaDABofhv2RSybxkfVX
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_avax_usdn_direct_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_avax_usdn_direct_extractor
    tty: true
    restart: always
    command: --config usdn_avax.json --type "waves-evm-direct"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8310:8090"
    networks:
      - app-network
  susy_avax_usdn_reverse_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_avax_usdn_reverse_extractor
    tty: true
    restart: always
    command: --config usdn_avax.json --type "waves-evm-reverse"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8311:8090"
    networks:
      - app-network
  susy_bsc_usdn_direct_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_bsc_usdn_direct_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=0x3a9e63494D6258FEEAA2a348C519cc14C6df8827
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_bsc_usdn_reverse_oracle:
    image: gravityhuborg/gravity-oracle:master
    container_name: susy_bsc_usdn_reverse_oracle
    tty: true
    restart: always
    environment:
      - NEBULA_ADDRESS=3P5SKDHPTBF1Spe1nzEA11GFjfuv1V59zVd
    volumes:
      - /home/main2:/etc/gravity
    networks:
      - app-network
  susy_bsc_usdn_direct_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_bsc_usdn_direct_extractor
    tty: true
    restart: always
    command: --config usdn_bsc.json --type "waves-evm-direct"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8323:8090"
    networks:
      - app-network
  susy_bsc_usdn_reverse_extractor:
    image: gravityhuborg/gravity-data-extractor:master
    container_name: susy_bsc_usdn_reverse_extractor
    tty: true
    restart: always
    command: --config usdn_bsc.json --type "waves-evm-reverse"
    volumes:
      - /home/extractor-configs:/etc/extractor
    ports:
      - "8324:8090"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
